version: '3.7'

volumes:
    postgres-data: {}
    redis-data: {}
    redis-insight-data: {}

services:
    router:
        build: services/router
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        network_mode: "host"

    frontend:
        build: services/frontend
        depends_on:
            - postgres
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/application:cached"
        extra_hosts:
            - "jackett.${PROJECT_ROOT_DOMAIN}:172.17.0.1"
            - "redis.${PROJECT_ROOT_DOMAIN}:172.17.0.1"
            - "transmission.${PROJECT_ROOT_DOMAIN}:172.17.0.1"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.rule=Host(${PROJECT_DOMAINS})"
            - "traefik.http.routers.${PROJECT_NAME}-frontend.tls=true"
            - "traefik.http.routers.${PROJECT_NAME}-frontend-unsecure.rule=Host(${PROJECT_DOMAINS})"
            # Comment the next line to be able to access frontend via HTTP instead of HTTPS
            - "traefik.http.routers.${PROJECT_NAME}-frontend-unsecure.middlewares=redirect-to-https@file"

    postgres:
        build: services/postgres
        environment:
            - POSTGRES_USER=quasarr
            - POSTGRES_PASSWORD=quasarr
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data

    cron:
        build: services/cron
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/application:cached"

    redis:
        image: redis:5
        volumes:
            - "redis-data:/data"

    redis-insight:
        image: redislabs/redisinsight:1.3.1
        volumes:
            - "redis-insight-data:/db"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-redis.rule=Host(`redis.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-redis.tls=true"

    jackett:
        image: linuxserver/jackett
        restart: unless-stopped
        volumes:
            - ./jackett/config:/config
            - ./jackett/downloads:/downloads
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-jackett.rule=Host(`jackett.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-jackett.tls=true"

    transmission:
        image: linuxserver/transmission
        restart: unless-stopped
        volumes:
            - ./library/downloads:/downloads
            - ./transmission/config:/config
            - ./transmission/watch:/watch
        environment:
            - TRANSMISSION_WEB_HOME=/combustion-release/
        extra_hosts:
            - "transmission.${PROJECT_ROOT_DOMAIN}:172.17.0.1"
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${PROJECT_NAME}-transmission.rule=Host(`transmission.${PROJECT_ROOT_DOMAIN}`)"
            - "traefik.http.routers.${PROJECT_NAME}-transmission.tls=true"
